export enum MavComponent {
	MAV_COMP_ID_ALL = 0, // Used to broadcast messages to all components of the receiving system. Components should attempt to process messages with this component ID and forward to components on any other interfaces.
	MAV_COMP_ID_AUTOPILOT1 = 1, // System flight controller component ("autopilot"). Only one autopilot is expected in a particular system.
	MAV_COMP_ID_CAMERA = 100, // Camera #1.
	MAV_COMP_ID_CAMERA2 = 101, // Camera #2.
	MAV_COMP_ID_CAMERA3 = 102, // Camera #3.
	MAV_COMP_ID_CAMERA4 = 103, // Camera #4.
	MAV_COMP_ID_CAMERA5 = 104, // Camera #5.
	MAV_COMP_ID_CAMERA6 = 105, // Camera #6.
	MAV_COMP_ID_SERVO1 = 140, // Servo #1.
	MAV_COMP_ID_SERVO2 = 141, // Servo #2.
	MAV_COMP_ID_SERVO3 = 142, // Servo #3.
	MAV_COMP_ID_SERVO4 = 143, // Servo #4.
	MAV_COMP_ID_SERVO5 = 144, // Servo #5.
	MAV_COMP_ID_SERVO6 = 145, // Servo #6.
	MAV_COMP_ID_SERVO7 = 146, // Servo #7.
	MAV_COMP_ID_SERVO8 = 147, // Servo #8.
	MAV_COMP_ID_SERVO9 = 148, // Servo #9.
	MAV_COMP_ID_SERVO10 = 149, // Servo #10.
	MAV_COMP_ID_SERVO11 = 150, // Servo #11.
	MAV_COMP_ID_SERVO12 = 151, // Servo #12.
	MAV_COMP_ID_SERVO13 = 152, // Servo #13.
	MAV_COMP_ID_SERVO14 = 153, // Servo #14.
	MAV_COMP_ID_GIMBAL = 154, // Gimbal component.
	MAV_COMP_ID_LOG = 155, // Logging component.
	MAV_COMP_ID_ADSB = 156, // Automatic Dependent Surveillance-Broadcast (ADS-B) component.
	MAV_COMP_ID_OSD = 157, // On Screen Display (OSD) devices for video links.
	MAV_COMP_ID_PERIPHERAL = 158, // Generic autopilot peripheral component ID. Meant for devices that do not implement the parameter microservice.
	MAV_COMP_ID_QX1_GIMBAL = 159, // Gimbal ID for QX1.
	MAV_COMP_ID_FLARM = 160, // FLARM collision alert component.
	MAV_COMP_ID_MISSIONPLANNER = 190, // Component that can generate/supply a mission flight plan (e.g. GCS or developer API).
	MAV_COMP_ID_PATHPLANNER = 195, // Component that finds an optimal path between points based on a certain constraint (e.g. minimum snap, shortest path, cost, etc.).
	MAV_COMP_ID_OBSTACLE_AVOIDANCE = 196, // Component that plans a collision free path between two points.
	MAV_COMP_ID_VISUAL_INERTIAL_ODOMETRY = 197, // Component that provides position estimates using VIO techniques.
	MAV_COMP_ID_IMU = 200, // Inertial Measurement Unit (IMU) #1.
	MAV_COMP_ID_IMU_2 = 201, // Inertial Measurement Unit (IMU) #2.
	MAV_COMP_ID_IMU_3 = 202, // Inertial Measurement Unit (IMU) #3.
	MAV_COMP_ID_GPS = 220, // GPS #1.
	MAV_COMP_ID_GPS2 = 221, // GPS #2.
	MAV_COMP_ID_UDP_BRIDGE = 240, // Component to bridge MAVLink to UDP (i.e. from a UART).
	MAV_COMP_ID_UART_BRIDGE = 241, // Component to bridge to UART (i.e. from UDP).
	MAV_COMP_ID_SYSTEM_CONTROL = 250, // Component for handling system messages (e.g. to ARM, takeoff, etc.).
	MAV_COMPONENT_ENUM_END = 251, // 
}